### ISSUE TITLE
Potential dependency conflicts between frida-util and frida

### ISSUE THREAD

**Issue by NeolithEra** [bannsec/frida-util#1]
Hi, as shown in the following full dependency graph of  **_frida-util_**, frida-util requires _**frida**_ (the latest version)， while the installed version of **_frida-tools_**(2.0.2) requires _**frida<13.0.0,>=12.5.3**_.

According to Pip's “first found wins” installation strategy, _**frida 12.6.11**_ is the actually installed version.  

Although the first found package version _**frida 12.6.11**_ just satisfies the later dependency constraint （_**frida<13.0.0,>=12.5.3**_), it will lead to a build failure once developers release a newer version of frida whose version number is greater than 13.0.0.

It'll be good if we just adjust the constraints (if possible) here, which can avoid potential dependency conflicts in the near future.

### Dependency tree--------
```
frida-util<version range:>
| +-appdirs<version range:>
| +-bs4<version range:>
| | +-beautifulsoup4<version range:>
| +-colorama<version range:>
| +-frida<version range:>
| +-frida-tools<version range:>
| | +-colorama<version range:>=0.2.7,<1.0.0>
| | +-frida<version range:<13.0.0,>=12.5.3>
| | +-prompt-toolkit<version range:>=2.0.0,<3.0.0>
| | | +-pygments<version range:>
| | | +-six<version range:>=1.8.0>
| | | +-wcwidth<version range:>
| | +-pygments<version range:<3.0.0,>=2.0.2>
| +-pefile<version range:>
| | +-future<version range:>
| +-prettytable<version range:>
| +-psutil<version range:>
| +-pyelftools<version range:>
| +-requests<version range:>
| +-termcolor<version range:>
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggestion:
1.	Fix your direct dependencies to be **_frida<13.0.0,>=12.5.3_** and **_frida-tools==2.0.2_**, to remove this conflict. 
        I have checked this revision will not affect your downstream projects now.

2. Remove the direct dependency frida, then you can use this package transitively introduced by frida-tools.

Which solution do you prefer, 1 or 2?
Please let me know your choice, then I can submit a PR to fix it.

Thanks!

**Comment by NeolithEra** [comment]
@bannsec Could you help review this issue?

**Comment by bannsec** [comment]
Thanks for the info. Wasn't actually using that dependency so i just removed it.
